# Generated by Django 4.2.6 on 2023-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='aparttments',
        ),
        migrations.AddField(
            model_name='projects',
            name='apartments',
            field=models.ManyToManyField(related_name='projects', to='mainpage.apartment'),
        ),
    ]
